app/home/forms.py
# coding:utf-8
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, TextAreaField, FileField
from wtforms.validators import DataRequired, Email, Regexp, EqualTo, ValidationError
from app.models import User


class RegistForm(FlaskForm):
    name = StringField(
        label="昵称",
        validators=[
            DataRequired("请输入昵称！")
        ],
        description="昵称",
        render_kw={
            "class": "form-control input-lg",
            "placeholder": "昵称"
        }
    )
    email = StringField(
        label="邮箱",
        validators=[
            DataRequired("请输入邮箱！"),
            Email("邮箱格式不正确")
        ],
        description="邮箱",
        render_kw={
            "class": "form-control input-lg",
            "placeholder": "邮箱"
        }
    )
    phone = StringField(
        label="手机",
        validators=[
            DataRequired("请输入手机！"),
            Regexp(r"1[3578]\d{9}")
        ],
        description="手机",
        render_kw={
            "class": "form-control input-lg",
            "placeholder": "手机"
        }
    )

    pwd = PasswordField(
        label="密码",
        validators=[
            DataRequired("请输入密码！")
        ],
        description="密码",
        render_kw={
            "class": "form-control input-lg",
            "placeholder": "请输入密码！"
        }
    )

    repwd = PasswordField(
        label="确认密码",
        validators=[
            DataRequired("请再次输入密码！"),
            EqualTo('pwd', "输入密码不一致！")

        ],
        description="确认密码",
        render_kw={
            "class": "form-control input-lg",
            "placeholder": "请再次输入密码！"
        }
    )

    submit = SubmitField(
        label="注册",
        render_kw={
            "class": "btn btn-lg btn-success btn-block"
        }
    )

    def validate_name(self, field):
        name = field.data
        name_count = User.query.filter_by(name=name).count()
        if name_count == 1:
            raise ValidationError("昵称已存在！")

    def validate_mail(self, field):
        email = field.data
        email_count = User.query.filter_by(email=email).count()
        if email_count == 1:
            raise ValidationError("邮箱已存在！")

    def validate_phone(self, field):
        phone = field.data
        phone_count = User.query.filter_by(phone=phone).count()
        if phone_count == 1:
            raise ValidationError("手机号码已存在！")


class LoginForm(FlaskForm):
    name = StringField(
        label="账号",
        validators=[
            DataRequired("请输入账号！")
        ],
        description="账号",
        render_kw={
            "class": "form-control input-lg",
            "placeholder": "账号"
        }
    )

    pwd = PasswordField(
        label="密码",
        validators=[
            DataRequired("请输入密码！")
        ],
        description="密码",
        render_kw={
            "class": "form-control input-lg",
            "placeholder": "请输入密码！"
        }
    )

    submit = SubmitField(
        label="登录",
        render_kw={
            "class": "btn btn-lg btn-success btn-block"
        }
    )

    def validate_name(self, field):
        name = field.data
        name_count = User.query.filter_by(name=name).count()
        if name_count == 0:
            raise ValidationError("账号不存在！")


class UserdetailForm(FlaskForm):
    name = StringField(
        label="昵称",
        validators=[
            DataRequired("请输入昵称！")
        ],
        description="昵称",
        render_kw={
            "class": "form-control input-lg",
            "placeholder": "昵称",
            "autofocus": "autofocus"
        }
    )
    email = StringField(
        label="邮箱",
        validators=[
            DataRequired("请输入邮箱！"),
            Email("邮箱格式不正确")
        ],
        description="邮箱",
        render_kw={
            "class": "form-control input-lg",
            "placeholder": "邮箱",
            "autofocus": "autofocus"
        }
    )
    phone = StringField(
        label="手机",
        validators=[
            DataRequired("请输入手机！"),
            Regexp(r"1[3578]\d{9}")
        ],
        description="手机",
        render_kw={
            "class": "form-control input-lg",
            "placeholder": "手机",
            "autofocus": "autofocus"
        }
    )

    face = FileField(
        label="头像",
        validators=[
            DataRequired("请上传头像！")
        ],
        description="头像"
    )

    info = TextAreaField(
        label="简介",
        validators=[
            DataRequired("请输入简介")
        ],
        description="简介",
        render_kw={
            "class": "form-control",
            "rows": "10",
        }
    )

    submit = SubmitField(
        label='保存修改',

        render_kw={
            "href": "user.html",
            "class": "btn btn-success"
        }
    )


class PwdForm(FlaskForm):
    old_pwd = PasswordField(
        label='旧密码',
        validators=[
            DataRequired("请输入旧密码！")
        ],
        description='旧密码',
        render_kw={
            "class": "form-control",
            "placeholder": "请输入旧密码！",
            'required': "required"

        }
    )

    new_pwd = PasswordField(
        label='新密码',
        validators=[
            DataRequired("请输入新密码！"),

        ],
        description='新密码',
        render_kw={
            "class": "form-control",
            "placeholder": "请输入新密码！",
            'required': "required"

        }
    )

    submit = SubmitField(
        '修改密码',
        render_kw={
            "class": "btn btn-success"
        }
    )


class CommentForm(FlaskForm):
    content = TextAreaField(
        label="内容",
        validators=[
            DataRequired("请输入评论内容")
        ],
        description="内容",
        render_kw={
            "id": "input_content",
            "rows": "10"
        }
    )

    submit = SubmitField(
        label='提交评论',
        render_kw={
            "class": "btn btn-success",
            "id": "btn-sub"
        }
    )

app/home/__init__.py
# coding: utf-8
from flask import Blueprint


home = Blueprint('home', __name__)

import app.home.views

app/home/views.py
#  coding:utf-8
from . import home
from flask import render_template, redirect, url_for, flash, request, session, Response
from app.home.forms import RegistForm, LoginForm, UserdetailForm, PwdForm, CommentForm
from app.models import User, Userlog, Comment, Movie, Moviecol, Tag, Preview
from werkzeug.security import generate_password_hash
from werkzeug.utils import secure_filename
from app import db, app, rd
from functools import wraps
import os, json, uuid
from datetime import datetime


def change_filename(filename):
    fileinfo = os.path.splitext(filename)
    filename = datetime.now().strftime("%Y%m%d%H%M%S") + str(uuid.uuid4().hex) + fileinfo[-1]
    return filename


def admin_login_req(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        if "user" not in session:
            return redirect(url_for("user.login", next=request.url))
        return f(*args, **kwargs)

    return decorated_function


@admin_login_req
@home.route('/<int:page>/', methods=['GET'])
def index(page=None):
    tags = Tag.query.all()
    page_data = Movie.query
    tid = request.args.get("tid", 0)
    # 评论
    if int(tid) != 0:
        page_data = page_data.filter_by(tag_id=int(tid))
    # 星级
    star = request.args.get("star", 0)
    if int(star) != 0:
        page_data = page_data.filter_by(star=int(star))
    # 播放量
    pn = request.args.get("pn", 0)
    if int(pn) != 0:
        if int(pn) == 1:
            page_data = page_data.order_by(Movie.playnum.desc())
        else:
            page_data = page_data.order_by(Movie.playnum.asc())
    # 评论量
    cn = request.args.get("cn", 0)
    if int(cn) != 0:
        if int(cn) == 1:
            page_data = page_data.order_by(Movie.commentnum.desc())
        else:
            page_data = page_data.order_by(Movie.commentnum.asc())
    # 上映时间
    rt = request.args.get("rt", 0)
    if int(rt) != 0:
        if int(rt) == 1:
            page_data = page_data.order_by(Movie.release.desc())
        else:
            page_data = page_data.order_by(Movie.release.asc())

    if page is None:
        page = 1
    page_data = page_data.paginate(page=page, per_page=12)
    p = dict(
        tid=tid,
        star=star,
        pn=pn,
        cn=cn,
        rt=rt,
    )
    return render_template("home/index.html", p=p, tags=tags, page_data=page_data)


@home.route('/login/', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        data = form.data
        user = User.query.filter_by(name=data['name']).first()
        if not user.check_pwd(data['pwd']):
            flash("密码错误", "err")
            return redirect(url_for("home.login"))
        session['user'] = user.name
        session['user_id'] = user.id

        userlog = Userlog(
            user_id=user.id,
            ip=request.remote_addr
        )
        db.session.add(userlog)
        db.session.commit()
        flash("登录成功", "ok")
        return redirect(url_for("home.user"))

    return render_template("home/login.html", form=form)


@home.route('/logout/')
def logout():
    session.pop("user", None)
    session.pop("user_id", None)
    return redirect(url_for("home.login"))


@admin_login_req
@home.route('/regist/', methods=['GET', 'POST'])
def regist():
    form = RegistForm()
    if form.validate_on_submit():
        data = form.data
        user = User(
            name=data["name"],
            email=data["email"],
            phone=data["phone"],
            pwd=generate_password_hash(data["pwd"]),
            uuid=uuid.uuid4().hex
        )
        db.session.add(user)
        db.session.commit()
        flash("注册成功", "ok")
        redirect(url_for("home.regist"))
        userlog = Userlog(
            user_id=user.id,
            ip=request.remote_addr
        )
        db.session.add(userlog)
        db.session.commit()
    return render_template("home/regist.html", form=form)


@admin_login_req
@home.route('/user/', methods=['GET', 'POST'])
def user():
    form = UserdetailForm()
    user = User.query.get_or_404(int(session['user_id']))
    if request.method == "GET":
        form.name.data = user.name
        form.email.data = user.email
        form.phone.data = user.phone
        form.info.data = user.info
        form.face.validators = []

    if form.validate_on_submit():
        data = form.data
        name_count = User.query.filter_by(name=data['name']).count()
        phone_count = User.query.filter_by(name=data['phone']).count()
        email_count = User.query.filter_by(name=data['email']).count()
        if not os.path.exists(app.config['USER_DIR']):
            os.makedirs(app.config["USER_DIR"])
            os.chmod(app.config["USER_DIR"], 'rw')

        if form.face.data.filename != "":
            file_logo = secure_filename(form.face.data.filename)
            user.face = change_filename(file_logo)
            form.face.data.save(app.config["USER_DIR"] + user.face)

        if email_count == 1 and user.email != data['email']:
            flash("用户邮箱已存在", "err")
            return redirect(url_for("home.user"))
        if phone_count == 1 and user.email != data['phone']:
            flash("用户手机已存在", "err")
            return redirect(url_for("home.user"))
        if name_count == 1 and user.name != data['name']:
            flash("用户昵称已存在", "err")
            return redirect(url_for("home.user"))
        user.name = data["name"]
        user.email = data["email"]
        user.phone = data["phone"]
        user.info = data["info"]

        db.session.add(user)
        db.session.commit()
        flash("用户资料修改成功", "ok")
    return render_template("home/user.html", form=form, user=user)


@admin_login_req
@home.route('/pwd/', methods=['GET', "POST"])
def pwd():
    form = PwdForm()
    if form.validate_on_submit():
        data = form.data
        print('0')
        user = User.query.filter_by(id=session['user_id']).first()
        if not user.check_pwd(data['old_pwd']):
            print('1')
            flash("旧密码错误", 'err')
            return redirect(url_for('home.pwd'))
        if data['old_pwd'] == data['new_pwd']:
            flash("新旧密码相同", 'err')
            return redirect(url_for('home.pwd'))
        print('3')
        user.pwd = generate_password_hash(data['new_pwd'])
        db.session.add(user)
        db.session.commit()
        flash("修改密码成功，请重新登录", 'ok')
        return redirect(url_for('home.login'))
    return render_template("home/pwd.html", form=form)


@admin_login_req
@home.route('/comments/<int:page>/', methods=['GET'])
def comments(page=None):
    if page is None:
        page = 1
    page_data = Comment.query.join(
        Movie
    ).join(
        User
    ).filter(
        Movie.id == Comment.movie_id,
        User.id == Comment.user_id
    ).order_by(
        Comment.addtime.desc()
    ).paginate(page=page, per_page=10)
    return render_template("home/comments.html", page_data=page_data)


@admin_login_req
@home.route('/loginlog/<int:page>/', methods=['GET'])
def loginlog(page=None):
    if page is None:
        page = 1
    page_data = Userlog.query.join(
        User
    ).filter(
        User.id == Userlog.user_id
    ).order_by(
        Userlog.addtime.desc()
    ).paginate(page=page, per_page=10)
    return render_template("home/loginlog.html", page_data=page_data)


@admin_login_req
@home.route('/moviecol/add/', methods=['GET'])
def moviecol_add():
    mid = request.args.get("mid", "")
    uid = request.args.get("uid", "")
    col_count = Moviecol.query.filter(
        Moviecol.movie_id == int(mid),
        Moviecol.user_id == int(uid)
    ).count()
    if col_count == 1:
        data = dict(ok=0)
    if col_count == 0:
        moviecol = Moviecol(
            user_id=uid,
            movie_id=mid,
        )
        db.session.add(moviecol)
        db.session.commit()
        data = dict(ok=1)
    return json.dumps(data)


@admin_login_req
@home.route('/moviecol/<int:page>/', methods=['GET'])
def moviecol(page=None):
    if page is None:
        page = 1
    page_data = Moviecol.query.join(
        Movie
    ).join(
        User
    ).filter(
        Movie.id == Moviecol.movie_id,
        User.id == session['user_id']
    ).order_by(
        Moviecol.addtime.desc()
    ).paginate(page=page, per_page=10)
    return render_template("home/moviecol.html", page_data=page_data)


@admin_login_req
@home.route('/animation/', methods=['GET'])
def animation():
    preview_data = Preview.query.all()
    return render_template("home/animation.html", preview_data=preview_data)


@admin_login_req
@home.route('/search/<int:page>/', methods=['GET'])
def search(page=None):
    if page is None:
        page = 1
    key = request.args.get("key", "")
    movie_count = Movie.query.filter(Movie.title.ilike("%" + key + "%")).count()
    page_data = Movie.query.filter(
        Movie.title.ilike("%" + key + "%")
    ).order_by(
        Movie.addtime.desc()
    ).paginate(page=page, per_page=10)
    page_data.key = key
    return render_template("home/search.html", movie_count=movie_count, page_data=page_data)


@admin_login_req
@home.route('/play/<int:id>/<int:page>', methods=['GET', 'POST'])
def play(id=None, page=None):
    form = CommentForm()

    movie = Movie.query.join(
        Tag
    ).filter(
        Tag.id == Movie.tag_id,
        Movie.id == int(id)
    ).first_or_404()

    if request.method == "GET":
        movie.playnum += 1
        db.session.add(movie)
        db.session.commit()

    if page is None:
        page = 1
    page_data = Comment.query.join(
        Movie
    ).join(
        User
    ).filter(
        Movie.id == id,
        User.id == Comment.user_id
    ).order_by(
        Comment.addtime.desc()
    ).paginate(page=page, per_page=10)

    if form.validate_on_submit():
        data = form.data
        comment = Comment(
            content=data['content'],
            movie_id=id,
            user_id=session['user_id']
        )

        db.session.add(comment)
        db.session.commit()

app/templates/home/home.html
<!doctype html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1 , user-scalable=no">
    <title>微电影</title>
    <link rel="shortcut icon" href="{{ url_for('static', filename='base/images/logo.png') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='base/css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='base/css/bootstrap-movie.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='base/css/animate.css') }}">
    <style>
        .navbar-brand>img {
            display: inline;
        }

    </style>
    <style>
        .media{
            padding:3px;
            border:1px solid #ccc
        }

    </style>
    {% block css %} {% endblock %}
</head>

<body>
<!--导航-->
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <!--小屏幕导航按钮和logo-->
        <div class="navbar-header">
            <button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="{{ url_for('home.index',page=1) }}" class="navbar-brand" style="width:250px;">
                <img src="{{ url_for('static', filename='base/images/logo.png')}}" style="height:30px;">&nbsp;微电影
            </a>
        </div>
        <!--小屏幕导航按钮和logo-->
        <!--导航-->
        <div class="navbar-collapse collapse">
            <form class="navbar-form navbar-left" role="search" style="margin-top:18px;">
                <div class="form-group input-group">
                    <input type="text" class="form-control" placeholder="请输入电影名！" id="key_movie">
                    <span class="input-group-btn">
                        <a class="btn btn-default" id="do_search"><span
                                class="glyphicon glyphicon-search"></span>&nbsp;搜索</a>
                    </span>
                </div>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a class="curlink" href="{{ url_for('home.index',page=1) }}"><span
                            class="glyphicon glyphicon-film"></span>&nbsp;电影</a>
                </li>
                <li>
                    <a class="curlink" href="{{ url_for('home.login') }}"><span
                            class="glyphicon glyphicon-log-in"></span>&nbsp;登录</a>
                </li>
                <li>
                    <a class="curlink" href="{{ url_for('home.regist') }}"><span
                            class="glyphicon glyphicon-plus"></span>&nbsp;注册</a>
                </li>
                <li>
                    <a class="curlink" href="{{ url_for('home.logout') }}"><span
                            class="glyphicon glyphicon-log-out"></span>&nbsp;退出</a>
                </li>
                <li>
                    <a class="curlink" href="{{ url_for('home.user') }}"><span class="glyphicon glyphicon-user"></span>&nbsp;会员</a>
                </li>
            </ul>
        </div>
        <!--导航-->

    </div>
</nav>
<!--导航-->
<!--内容-->
<div class="container" style="margin-top:76px">
    {% block content %} {% endblock %}
</div>
<!--内容-->
<!--底部-->
<footer>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p>
                    ©&nbsp;2017&nbsp;flaskmovie.imooc.com&nbsp;京ICP备 13046642号-2
                </p>
            </div>
        </div>
    </div>
</footer>
<!--底部-->
<script src="{{ url_for('static', filename='base/js/jquery.min.js')}}"></script>
<script src="{{ url_for('static', filename='base/js/bootstrap.min.js')}}"></script>
<script src="{{ url_for('static', filename='base/js/jquery.singlePageNav.min.js') }}"></script>
<script src="{{ url_for('static', filename='base/js/wow.min.js')}}"></script>
<script src="{{ url_for('static', filename='lazyload/jquery.lazyload.min.js')}}"></script>
<script src="//cdn.bootcss.com/holder/2.9.4/holder.min.js"></script>
<script>
    $(function() {
        new WOW().init();
    })




</script>
<script>
    $(document).ready(function() {
        $("img.lazy").lazyload({
            effect: "fadeIn"
        });
        $("#do_search").click(function(){
            var key = $("#key_movie").val();
            location.href="{{url_for('home.search',page=1)}}?key=" + key;

        });
    });




</script>
{% block js %} {% endblock %}
</body>
</html>

app/templates/home/index.html
{% extends "home/layout.html" %}
{% import "ui/home_page.html" as pg %}
{% block content %}
<!--热门电影-->
<section id="hotmovie" style="margin-top:76px">
    <div class="container">
        <div class="row wow fadeInRight" data-wow-delay="0.6s">
            <div class="row">
                <iframe class="wow fadeIn" width="100%" height="375px" frameborder=0 scrolling=no
                        src="{{ url_for('home.animation') }}"></iframe>
            </div>
        </div>
    </div>
</section>
<!--热门电影-->
<!--电影列表-->
<section id="movielist">
    <div class="container">
        <div class="row wow fadeIn" data-wow-delay="0.6s">
            <div class="col-md-12 table-responsive">
                <table class="table text-left table-bordered" id="movietags">
                    <tr>
                        <td style="width:10%;">电影标签</td>
                        <td style="width:90%;">
                            {% for tag in tags %}
                            <a href="{{ url_for('home.index',page=1)}}?tid={{tag.id}}&star={{p['star']}}&rt={{p['rt']}}&pn={{p['pn']}}&cn={{p['cn']}}"
                               class="label label-info" >
                                <span class="glyphicon glyphicon-tag"></span>&nbsp;{{tag.name}}</a>
                            {% endfor %}
                    <tr>
                        <td>电影星级</td>
                        <td>
                            {% for star in range(1,6) %}
                            <a href="{{ url_for('home.index',page=1)}}?tid={{p['tid']}}&star={{ star }}&rt={{p['rt']}}&pn={{p['pn']}}&cn={{p['cn']}}"
                               class="label label-warning"><span class="glyphicon glyphicon-star"></span>&nbsp;{{star}}星</a>
                            {% endfor %}
                        </td>
                    </tr>
                    <tr>
                        <td>上映时间</td>
                        <td>
                            <a href="{{ url_for('home.index',page=1)}}?tid={{p['tid']}}&star={{ p['star'] }}&rt=1&pn={{p['pn']}}&cn={{p['cn']}}"
                                    class="label label-default"><span class="glyphicon glyphicon-time"></span>&nbsp;最近</span>
                            </a>
                            <a href="{{ url_for('home.index',page=1)}}?tid={{p['tid']}}&star={{ p['star'] }}&rt=2&pn={{p['pn']}}&cn={{p['cn']}}"
                                    class="label label-default"><span class="glyphicon glyphicon-time"></span>&nbsp;更早</span>
                            </a>
                        </td>
                    </tr>
                    <tr>
                        <td>播放数量</td>
                        <td>
                            <a href="{{ url_for('home.index',page=1)}}?tid={{p['tid']}}&star={{ p['star'] }}&rt={{p['rt']}}&pn=1&cn={{p['cn']}}"
                                    class="label label-success"><span class="glyphicon glyphicon-arrow-down"></span>&nbsp;从高到底</span>
                            </a>
                            &nbsp;
                            <a
                                    href="{{ url_for('home.index',page=1)}}?tid={{p['tid']}}&star={{ p['star'] }}&rt={{p['rt']}}&pn=2&cn={{p['cn']}}"class="label label-danger"><span
                                    class="glyphicon glyphicon-arrow-up"></span>&nbsp;从低到高</span></a>
                        </td>
                    </tr>
                    <tr>
                        <td>评论数量</td>
                        <td>
                            <a href="{{ url_for('home.index',page=1)}}?tid={{p['tid']}}&star={{ p['star'] }}&rt={{p['rt']}}&pn={{p['pn']}}&cn=1"
                                    class="label label-success"><span class="glyphicon glyphicon-arrow-down"></span>&nbsp;从高到底</span>
                            </a>
                            &nbsp;
                            <a href="{{ url_for('home.index',page=1)}}?tid={{p['tid']}}&star={{ p['star'] }}&rt={{p['rt']}}&pn={{p['pn']}}&cn=2"
                                    class="label label-danger"><span
                                    class="glyphicon glyphicon-arrow-up"></span>&nbsp;从低到高</span></a>
                        </td>
                    </tr>
                </table>
            </div>
            {% for v in page_data.items %}
            <div class="col-md-3">
                <div class="movielist text-center">
                    <!--<img data-original="holder.js/262x166"
                             class="img-responsive lazy center-block" alt="">-->
                    <img src="{{url_for('static',filename='uploads/'+v.logo)}}"  style="width:262px;height:166px;" class="img-responsive center-block" alt="">
                    <div class="text-left" style="margin-left:auto;margin-right:auto;width:210px;">
                        <span style="color:#999;font-style: italic;">{{ v.title }}</span><br>
                        <div>
                            {% for s in range(v.star) %}
                            <span class="glyphicon glyphicon-star" style="color:#FFD119"></span>
                            {% endfor %}
                            {% for v in range(5-v.star) %}
                            <span class="glyphicon glyphicon-star-empty" style="color:#FFD119"></span>
                            {% endfor %}
                        </div>
                    </div>
                    <a href="{{ url_for('home.play',id=v.id ,page=1) }}" class="btn btn-primary" target="_blank"
                       role="button"><span
                            class="glyphicon glyphicon-play"></span>&nbsp;播放</a>
                </div>
            </div>
            {% endfor %}
            <div class="col-md-12">
                <nav aria-label="Page navigation">
                    {{ pg.page(page_data,'home.index')}}
                    </ul>
                </nav>
            </div>
        </div>
    </div>
</section>
<!--电影列表-->
{% endblock %}

app/templates/home/menu.html
<div class="col-md-3">
    <div class="list-group">
        <a id="m-1" href="{{url_for('home.user')}}" class="list-group-item">
            <span class="glyphicon glyphicon-user"></span>&nbsp;会员中心
        </a>
        <a id="m-2" href="{{url_for('home.pwd')}}" class="list-group-item">
            <span class="glyphicon glyphicon-lock"></span>&nbsp;修改密码
        </a>
        <a id="m-3" href="{{url_for('home.comments',page=1)}}" class="list-group-item">
            <span class="glyphicon glyphicon-comment"></span>&nbsp;评论记录
        </a>
        <a id="m-4" href="{{url_for('home.loginlog',page=1)}}" class="list-group-item">
            <span class="glyphicon glyphicon-calendar"></span>&nbsp;登录日志
        </a>
        <a id="m-5" href="{{url_for('home.moviecol',page=1)}}" class="list-group-item">
            <span class="glyphicon glyphicon-heart"></span>&nbsp;收藏电影
        </a>
    </div>
</div>

app/templates/home/moviecol.html
{% extends "home/home.html" %}
{% import "ui/home_page.html" as pg %}

{% block css %}
<style>
    .col-lg-1, .col-lg-10, .col-lg-11, .col-lg-12, .col-lg-2, .col-lg-3, .col-lg-4, .col-lg-5, .col-lg-6, .col-lg-7, .col-lg-8, .col-lg-9, .col-md-1, .col-md-10, .col-md-11, .col-md-12, .col-md-2, .col-md-3, .col-md-4, .col-md-5, .col-md-6, .col-md-7, .col-md-8, .col-md-9, .col-sm-1, .col-sm-10, .col-sm-11, .col-sm-12, .col-sm-2, .col-sm-3, .col-sm-4, .col-sm-5, .col-sm-6, .col-sm-7, .col-sm-8, .col-sm-9, .col-xs-1, .col-xs-10, .col-xs-11, .col-xs-12, .col-xs-2, .col-xs-3, .col-xs-4, .col-xs-5, .col-xs-6, .col-xs-7, .col-xs-8, .col-xs-9{
            padding-right: 3px;
            padding-left: 3px;
        }



</style>
{% endblock %}

{% block content %}
{% include "home/menu.html" %}
<div class="col-md-9">
    <div class="panel panel-warning">
        <div class="panel-heading">
            <h3 class="panel-title">
                <span class="glyphicon glyphicon-map-marker"></span>&nbsp;
                收藏电影
            </h3>
        </div>
        <div class="panel-body">
            <div class="col-md-12">
                {% for v in page_data.items %}
                <div class="media">
                    <div class="media-left">
                        <a href="{{ url_for('home.play',id=v.movie.id,page=1)}}">
                            <img class="media-object" src="{{url_for('static',filename='uploads/'+v.movie.logo)}}"
                                 width="140px" height="70px" alt="环太平洋">
                        </a>
                    </div>
                    <div class="media-body">
                        <h4 class="media-heading">{{v.movie.title}}
                            <a href="{{ url_for('home.play',id=v.movie.id,page=1)}}" class="label label-primary pull-right">
                                <span class="glyphicon glyphicon-play"></span>播放影片</a></h4>
                        {{v.movie.info}}
                    </div>
                </div>
                {% endfor %}
            </div>
            <div class="col-md-12 text-center" style="margin-top:6px;">
                {{ pg.page(page_data,'home.moviecol')}}
            </div>
        </div>
    </div>
</div>
{% block js%}
<script>
    $(document).ready(function{
        $("#m-5),add.Class("active");



</script>
{% endblock %}
{% endblock %}